id: P006934
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ6024
  title: འཇའ་ཚོན་སྙིང་པོའི་རང་རྣམ
  author: ''
  volumes:
    3926ac98eb94407d980cc2f03d5f7fd6:
      image_group_id: I1KG993
      title: ''
      volume_number: 1
      total_pages: 428
ebook_metadata:
  title: འཇའ་ཚོན་སྙིང་པོའི་རང་རྣམ
  author: ''
  sku: P006934
  cover: cover.jpg
  layers:
  - pagination
