id: P006934
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:35.203293
source_metadata:
  id: bdr:W2CZ6024
  title: འཇའ་ཚོན་སྙིང་པོའི་རང་རྣམ
  author: ''
  volumes:
    5dc1e7924b3f44b499ac5843448101b2:
      image_group_id: I1KG993
      title: Volume 1 of 'ja' tshon snying po'i rang rnam
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
