id: I79B336D9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:54:50+00:00'
last_modified: '2022-06-08T12:39:29.652603+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6024
  title: འཇའ་ཚོན་སྙིང་པོའི་རང་རྣམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3890':
      image_group_id: I1KG993
      title: Volume 1 of 'ja' tshon snying po'i rang rnam
      total_pages: 428
      order: 1
      base_file: 3890.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
